services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile.local
      args:
        - USER=${DOCKER_USER}
        - UID=${DOCKER_USER_UID}
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "8116:80"
    depends_on:
      - db
      # - redis
      # - minio
    container_name: ${PROJECT:-primefoods}_app
    hostname: app
    networks:
      - appnet

  db:
    image: postgres:15-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./data/db:/var/lib/postgresql/data:rw
    container_name: ${PROJECT:-primefoods}_db
    ports:
      - "5432:5432"
    hostname: db
    networks:
      - appnet

  pgadmin:
      image: dpage/pgadmin4:7
      user: "0:0"
      container_name: ${PROJECT:-primefoods}_pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: postgres@mail.ru
        PGADMIN_DEFAULT_PASSWORD: dbpass11
      ports:
        - "5050:80"
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
        - ./data/pgadmin:/var/lib/pgadmin
      networks:
        - appnet

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8482:8080"
    container_name: ${PROJECT:-primefoods}_adminer
    hostname: adm
    networks:
      - appnet

  # redis:
  #   build:
  #     context: .
  #     dockerfile: docker/redis/Dockerfile
  #   container_name: ${PROJECT}_redis
  #   hostname: redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./data/redis:/root/redis
  #   environment:
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #     - REDIS_PORT=6379
  #   #      - REDIS_DATABASES=16
  #   networks:
  #     - appnet

  # minio:
  #   image: minio/minio:RELEASE.2023-10-07T15-07-38Z
  #   container_name: ${PROJECT}_minio
  #   hostname: minio
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/s3:/data
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   environment:
  #     MINIO_ROOT_USER: ${MINIO_USER}
  #     MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
  #   command: server --address ":9000" --console-address ":9001" /data
  #   networks:
  #     - appnet

  mailhog:
     image: mailhog/mailhog
     container_name: ${PROJECT:-primefoods}_mailhog
     hostname: mailhog
     ports:
       - 8025:8025 # web ui
     networks:
       - appnet

networks:
  appnet:
    name: appnet
    driver: bridge
